# Copyright 2021 Ocean Protocol Foundation
# SPDX-License-Identifier: Apache-2.0

version: '3'
services:
  ocean-provider:
    image: oceanprotocol/provider-py:local
    ports:
      - 8030:8030
    env_file:
      - compose-env-values
    volumes:
      - ${ARTIFACTS_FOLDER}:/usr/local/:ro
